---
- op: replace
  path: /spec/template/spec/sources/1/repoURL
  value: https://github.com/hugares/infra-deployments.git
- op: replace
  path: /spec/template/spec/sources/1/targetRevision
  value: preview-hares-test-kubelet
