apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # only include secret for now, include base when ready to deploy kite to stone-stg-rh01
  # - ../../base
  - ../../base/external-secrets
patches:
  - path: database-secret-path.yaml
    target:
      name: database-secret
      group: external-secrets.io
      version: v1beta1
      kind: ExternalSecret
