resources:
- release-pipeline-resources-clusterrole.yaml
- release-service-config-rbac.yaml
- release-service-configurator-role.yaml
- release-team.yaml
- cronjobs/

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: release-service
