apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-core-service-controller-manager
  namespace: gitops
spec:
  template:
    spec:
      containers:
      - name: manager
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
