apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/
patches:
  - target:
      group: external-secrets.io
      version: v1beta1
      kind: ExternalSecret
      name: backup-s3-credentials
    path: backup-s3-credentials-patch.yaml
