resources:
- allow-argocd-to-manage.yaml
- argocd-permissions.yaml
- https://github.com/hugares/release-service/config/default?ref=6a417cde2a5818072a1b44a78d151c5b67336829
- release-pipeline-resources-clusterrole.yaml
- release-team.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/redhat-appstudio/release-service
  newName: quay.io/redhat-appstudio/release-service
  newTag: 56b15cd0564401261dd0944c215bb12b723e29fa

namespace: release-service

patches:
  - path: ./manager_resources_patch.yaml
