resources:
- allow-argocd-to-manage.yaml
- argocd-permissions.yaml
- https://github.com/hugares/release-service/config/default?ref=105705c8bf3586e1c4bce2aaf19b77a494ced963
- release-pipeline-resources-clusterrole.yaml
- release-team.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/redhat-appstudio/release-service
  newName: quay.io/redhat-appstudio/release-service
  newTag: 3ba78742daa454c0c82456c56140e9154f5f42fe

namespace: release-service

patches:
  - path: ./manager_resources_patch.yaml
