kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: build-maintainer
rules:
  - verbs:
      - get
      - list
      - patch
      - update
    apiGroups:
      - ''
    resources:
      - serviceaccounts
    resourceNames:
      - appstudio-pipeline # TODO: figure out how to 'gitops' this.
  - verbs:
      - list
    apiGroups:
      - ''
    resources:
      - secrets
  - verbs:
      - get
      - list
      - patch
      - update
    apiGroups:
      - pipelinesascode.tekton.dev
    resources:
      - repositories
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: build-maintainers
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: konflux-build
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: build-maintainer
